version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db 
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      subrede:
        ipv4_address: 172.20.31.2
  pgad:
    image: fenglc/pgadmin4:latest
    depends_on:
      - db
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      subrede:
        ipv4_address: 172.20.31.3
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      subrede:
        ipv4_address: 172.20.31.4
networks:
  subrede:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.31.0/16
         gateway: 172.20.31.1